### ISSUE TITLE
Detection content types

### ISSUE THREAD

**Issue by chrisr3d** [Neo23x0/sigma#117]
Hello there,
I am creating a MISP module to export attributes/objects from MISP as sigma rules and I read your wiki to find out about the specification and so on.

At the moment I did tests to create rules and I end up with something valid for your parser, because it has the required fields, like in the following example:
```
title: Sigma rule test 
logsource: 
    product: MISP 
detection: 
    selection: 
        ip-src: 
            - 1.2.3.4 
    condition: selection
```
But instead of `ip-src: 1.2.3.4`, any other combination of type and value seems to be valid for the parser

I also saw there is a list for the mapping between Sigma and ATP, so I wonder if there is a list of Sigma types (or documentation about it) I should use to map misp types with ?
