### ISSUE TITLE
Translate mapping

### ISSUE THREAD

**Issue by lprat** [Neo23x0/sigma#1285]
Hi,
I would like to know if the behavior when translating mapping is normal:
Mapping is https://github.com/google/timesketch/blob/master/data/sigma_config.yaml .

rule with pipe RE (lnx_susp_zenmap.yml)
```
title: Suspicious Installation of Zenmap
id: 5266a592-b793-11ea-b3de-0242ac130005
description: Detects suspicious installation of Zenmap
references:
    - https://rmusser.net/docs/ATT&CK-Stuff/ATT&CK/Discovery.html
author: Alexander Jaeger
date: 2020/06/26
modified: 2020/06/26
logsource:
    product: linux
    service: shell
detection:
    keywords:
        # Generic suspicious commands
        - Service|re: ".*apt\\-[a-z]{3} install zmap.*"
    condition: keywords
falsepositives:
    - Unknown
level: high
```

rule2 no "re" pipe and translated mapping field (lnx2_susp_zenmap.yml)
```
title: Suspicious Installation of Zenmap
id: 5266a592-b793-11ea-b3de-0242ac130005
description: Detects suspicious installation of Zenmap
references:
    - https://rmusser.net/docs/ATT&CK-Stuff/ATT&CK/Discovery.html
author: Alexander Jaeger
date: 2020/06/26
modified: 2020/06/26
logsource:
    product: linux
    service: shell
detection:
    keywords:
        # Generic suspicious commands
        - Service: ".*apt\\-[a-z]{3} install zmap.*"
    condition: keywords
falsepositives:
    - Unknown
level: high
```

rule3  no "re" pipe and no translated mapping field (lnx3_susp_zenmap.yml)
```
title: Suspicious Installation of Zenmap
id: 5266a592-b793-11ea-b3de-0242ac130005
description: Detects suspicious installation of Zenmap
references:
    - https://rmusser.net/docs/ATT&CK-Stuff/ATT&CK/Discovery.html
author: Alexander Jaeger
date: 2020/06/26
modified: 2020/06/26
logsource:
    product: linux
    service: shell
detection:
    keywords:
        # Generic suspicious commands
        - Services: ".*apt\\-[a-z]{3} install zmap.*"
    condition: keywords
falsepositives:
    - Unknown
level: high
```
create es queries with version sigmatools-0.18.1
```
# sigmac -c /etc/timesketch/sigma_config.yaml  -t es-qs /usr/local/src/timesketch/data/sigma/rules/lnx_susp_zenmap.yml 
(data_type:("shell\:zsh\:history" OR "bash\:history\:command" OR "apt\:history\:line" OR "selinux\:line") AND xml_string:/.*apt\-[a-z]{3} install zmap.*/)
# sigmac -c /etc/timesketch/sigma_config.yaml  -t es-qs /usr/local/src/timesketch/data/sigma/rules/lnx2_susp_zenmap.yml 
(data_type:("shell\:zsh\:history" OR "bash\:history\:command" OR "apt\:history\:line" OR "selinux\:line") AND xml_string.keyword:.*apt\\\-\[a\-z\]\{3\}\ install\ zmap.*)
# sigmac -c /etc/timesketch/sigma_config.yaml  -t es-qs /usr/local/src/timesketch/data/sigma/rules/lnx3_susp_zenmap.yml 
(data_type:("shell\:zsh\:history" OR "bash\:history\:command" OR "apt\:history\:line" OR "selinux\:line") AND Services.keyword:.*apt\\\-\[a\-z\]\{3\}\ install\ zmap.*)
```
Result show:
 - Rule1 with RE pipe dont add .keyword value to check in RAW
 - Rule2 if field in translate list but without RE then translate to xml_strings and add keyword to check in RAW
 - Rule3 if field not in translate list then add .keyword to name field to check in RAW

Why in use case 1 (rule 1), ".keyword" was not added?
Thank for your help.
