### ISSUE TITLE
Logical AND for Conditions

### ISSUE THREAD

**Issue by m1kemu** [Neo23x0/sigma#1310]
The Sigma specification states that multiple conditions are logically OR'd. For example, these two conditions would be logically OR'd if used in the same Sigma rule. For Example:

```
detection:
    selection:
        EventID: 5140
    filter:
        ShareName: '*$'
    timeframe: 5m
    condition: selection and not filter | count(ShareName) by SourceAddress, SubjectUserName > 3
    condition: selection and not filter | count(dest_ip) by SourceAddress, SubjectUserName > 20
```
    
It may be that the detection logic needs to detect activity where the count of distinct share names AND the count of destination hosts accessed reaches a specific threshold. This would require a logical AND of the conditions. The ability to chain conditions together with logic could also b useful, much like filters and selections can be chained together with boolean logic.

If I am misunderstanding the specification, and there is a way to achieve this, please let me know.
