### ISSUE TITLE
or list 

### ISSUE THREAD

**Issue by reveries0** [Neo23x0/sigma#190]
Hi, I think there are some cases not representables with sigma.
I need to write a query and get it translated with sigmac in elasticsearch dsl.
In this query I need to perform a search on a field, let's say a url, that get results if three regexp are in the url string.
For example, i need that the es-dsl query returns hits only if the following three expression (all of them) parsed with the same string (url) are true:` ".*git.*", ".*neo23.*", ".*sigma.*".`
So the query will return as results:
`https://github.com/Neo23x0/sigma/issues/new` or` https://github.com/Neo23x0/sigma/issues/test`
but not:
`https://github.com/Neo/sigma/issues/new`

If i write a list (properly indented) like the following:

```
selection:
url:
- ".*git.*"
- ".*neo23.*"
- ".*sigma.*"
```

they will be translated, as written in the docs, in a `{'bool': {'should' : [ ] }}` query. So, how can I represent that list that, _translated with sigmac_, will return a `{'bool':{'must':[ ]}}` query?
Thank you so much

**Comment by Neo23x0** [comment]
I'd write this like:

```
selection1:
   url: ".*git.*"
selection2:
   url: ".*neo23.*"
selection3:
   url: ".*sigma.*"
condition:
   all of them
```
