### ISSUE TITLE
Elastalert Integration - Sigmac not providing the right query format

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Neo23x0/sigma#203]
Good afternoon SIGMA team,

Im exporting all the rules to elastalert signatures, and I believe they are not being exported properly. For example, I pick this rule:
[sysmon_susp_vssadmin_ntds_activity.yml](https://github.com/Neo23x0/sigma/blob/92c0e0321a25d724a75e0654a1474aaa5f870342/rules/windows/sysmon/sysmon_susp_vssadmin_ntds_activity.yml)
```
title: Activity Related to NTDS.dit Domain Hash Retrieval
status: experimental
description: Detects suspicious commands that could be related to activity that uses volume shadow copy to steal and retrieve hashes from the NTDS.dit file remotely 
author: Florian Roth, Michael Haag
references:
    - https://www.swordshield.com/2015/07/getting-hashes-from-ntds-dit-file/
    - https://room362.com/post/2013/2013-06-10-volume-shadow-copy-ntdsdit-domain-hashes-remotely-part-1/
    - https://www.trustwave.com/Resources/SpiderLabs-Blog/Tutorial-for-NTDS-goodness-(VSSADMIN,-WMIS,-NTDS-dit,-SYSTEM)/
    - https://securingtomorrow.mcafee.com/mcafee-labs/new-teslacrypt-ransomware-arrives-via-spam/
logsource:
    product: windows
    service: sysmon
detection:
    selection:
        EventID: 1
        CommandLine:
            # Ransomware
            - 'vssadmin.exe Delete Shadows'
            # Hacking 
            - 'vssadmin create shadow /for=C:'
            - 'copy \\?\GLOBALROOT\Device\*\windows\ntds\ntds.dit'
            - 'copy \\?\GLOBALROOT\Device\*\config\SAM'
            - 'vssadmin delete shadows /for=C:'
            - 'reg SAVE HKLM\SYSTEM '
    condition: selection
fields:
    - CommandLine
    - ParentCommandLine
tags:
    - attack.credential_access
    - attack.t1003
falsepositives:
    - Administrative activity
level: high
```
When I pass that through Sigmac I get the following:
```
alert:
- debug
description: Detects suspicious commands that could be related to activity that uses
  volume shadow copy to steal and retrieve hashes from the NTDS.dit file remotely
filter:
- query:
    query_string:
      query: '(event_id:1 AND process_command_line:(vssadmin.exe\ Delete\ Shadows
        vssadmin\ create\ shadow\ \/for\=C\: copy\ \\\?\\GLOBALROOT\\Device\*\\windows\\ntds\\ntds.dit
        copy\ \\\?\\GLOBALROOT\\Device\*\\config\\SAM vssadmin\ delete\ shadows\ \/for\=C\:
        reg\ SAVE\ HKLM\\SYSTEM\ ))'
index: logs-endpoint-winevent-sysmon-*
name: Activity-Related-to-NTDS.dit-Domain-Hash-Retrieval_0
priority: 2
realert:
  minutes: 0
type: any
```
When I check my SIEM in my lab, I got 55 hits:

![image](https://user-images.githubusercontent.com/9653181/49496842-f6c98a00-f877-11e8-90cb-f1acd645acb6.png)

I then grabbed the query created in the elastalert rule created by Sigmac, and I can see how it is not formed properly:

![image](https://user-images.githubusercontent.com/9653181/49496918-25476500-f878-11e8-9882-af8b85a3fc04.png)

I checked the SIGMA fime and passed it through uncoder, and it provided the following query when it is translated to Elasticsearch:

```
(EventID:"1" AND CommandLine:("vssadmin.exe Delete Shadows" "vssadmin create shadow \/for\=C\:" "copy \\\?\\GLOBALROOT\\Device\*\\windows\\ntds\\ntds.dit" "copy \\\?\\GLOBALROOT\\Device\*\\config\\SAM" "vssadmin delete shadows \/for\=C\:" "reg SAVE HKLM\\SYSTEM "))
```
![image](https://user-images.githubusercontent.com/9653181/49496987-53c54000-f878-11e8-8904-8687de61688c.png)

When I applied that query to my lab, I get 0 hits of course. which sounds better to me:

![image](https://user-images.githubusercontent.com/9653181/49497044-79524980-f878-11e8-8f49-86c9553d9b4a.png)

So to summarize all:
Sigmac exports a SIGMA rule as an elastalert one without double quotes between each argument value passed to the "CommandLine" field:
```
alert:
- debug
description: Detects suspicious commands that could be related to activity that uses
  volume shadow copy to steal and retrieve hashes from the NTDS.dit file remotely
filter:
- query:
    query_string:
      query: '(event_id:1 AND process_command_line:(vssadmin.exe\ Delete\ Shadows
        vssadmin\ create\ shadow\ \/for\=C\: copy\ \\\?\\GLOBALROOT\\Device\*\\windows\\ntds\\ntds.dit
        copy\ \\\?\\GLOBALROOT\\Device\*\\config\\SAM vssadmin\ delete\ shadows\ \/for\=C\:
        reg\ SAVE\ HKLM\\SYSTEM\ ))'
index: logs-endpoint-winevent-sysmon-*
name: Activity-Related-to-NTDS.dit-Domain-Hash-Retrieval_0
priority: 2
realert:
  minutes: 0
type: any
```
If I add the right syntax to the query like the one provided by uncoder, then I got the following one which works:
```
(EventID:"1" AND CommandLine:("vssadmin.exe Delete Shadows" "vssadmin create shadow \/for\=C\:" "copy \\\?\\GLOBALROOT\\Device\*\\windows\\ntds\\ntds.dit" "copy \\\?\\GLOBALROOT\\Device\*\\config\\SAM" "vssadmin delete shadows \/for\=C\:" "reg SAVE HKLM\\SYSTEM "))
```

Let me know if this makes sense and if there is anything that can be done to craft the elastalert queries better. This is not the only alert that is giving me this issue. The following alerts were triggered in my lab and they are all not crafted properly:

![image](https://user-images.githubusercontent.com/9653181/49497267-08f7f800-f879-11e8-89de-dbe3a8c73945.png)

Lets check Mimikatz Use:

![image](https://user-images.githubusercontent.com/9653181/49497460-87549a00-f879-11e8-9f34-d5eae84c4896.png)

Anything that could be done on the SIgmac side? I havent looked at the code yet. Thank you in advance for your time
