### ISSUE TITLE
Elastalert Integration - One SIGMA Rule & Two Log Sources

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Neo23x0/sigma#205]
Good afternoon SIGMA Team,

I was wondering if it was intended to have two log sources under the same SIGMA rule. For example:

[Whoami Execution](https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_susp_whoami.yml) Under Builtin folder but showing also Sysmon as a log source.

```
---
action: global
title: Whoami Execution
status: experimental
description: 'Detects the execution of whoami, which is often used by attackers after exloitation / privilege escalation but rarely used by administrators' 
references:
    - https://twitter.com/haroonmeer/status/939099379834658817
    - https://twitter.com/c_APT_ure/status/939475433711722497
author: Florian Roth
date: 2018/05/22
tags:
    - attack.discovery
    - attack.t1033
detection:
    condition: selection
falsepositives: 
    - Admin activity
    - Scripts and administrative tools used in the monitored environment
level: high
---
logsource:
    product: windows
    service: sysmon
detection:
    selection:
        EventID: 1
        CommandLine: 'whoami'
---
logsource:
    product: windows
    service: security
    definition: 'Requirements: Audit Policy : Detailed Tracking > Audit Process creation, Group Policy : Administrative Templates\System\Audit Process Creation'
detection:
    selection:
        EventID: 4688
        NewProcessName: '*\whoami.exe'
```
When I translate this to an Elastalert Rule, I get ONE Elastalert rule file, but with two rules in it:

```
alert:
- debug
description: Detects the execution of whoami, which is often used by attackers after
  exloitation / privilege escalation but rarely used by administrators
filter:
- query:
    query_string:
      query: (event_id:"1" AND process_command_line:"whoami")
index: logs-endpoint-winevent-sysmon-*
name: Whoami-Execution_0
priority: 2
realert:
  minutes: 0
type: any

alert:
- debug
description: Detects the execution of whoami, which is often used by attackers after
  exloitation / privilege escalation but rarely used by administrators
filter:
- query:
    query_string:
      query: (event_id:"4688" AND process_path:"*\\whoami.exe")
index: logs-endpoint-winevent-security-*
name: Whoami-Execution-2_0
priority: 2
realert:
  minutes: 0
type: any
```

When I test the execution of **whoami** I can see one hit in my sysmon index as shown below, but no elastalert hits:

![image](https://user-images.githubusercontent.com/9653181/49507854-6b112700-f892-11e8-8fc1-e06dbb1507de.png)

I created a new rule inside of my elastalert rule folder from the logsource:Sysmon of the SIGMA rule above:

![image](https://user-images.githubusercontent.com/9653181/49508268-54b79b00-f893-11e8-8e48-bf1c3fc03e92.png)

I executed **whoami** , and I got a hit:

![image](https://user-images.githubusercontent.com/9653181/49508311-6f8a0f80-f893-11e8-82e7-1d139f64c15b.png)

![image](https://user-images.githubusercontent.com/9653181/49508341-83ce0c80-f893-11e8-9c4a-282cb8435599.png)

I believe having two log sources might not be a good idea either since there is a folder for builtin and a folder for sysmon. I dont know if it would make sense to keep them separate, but it is not helping integrations like elastalert. Any thoughts?? Thank you in advance 👍
