### ISSUE TITLE
Add placeholders

### ISSUE THREAD

**Issue by thomaspatzke** [Neo23x0/sigma#21]
Extension of configuration by placeholders that provide replacement values. Example (with Elasticsearch Query String syntax):
```
[...]
placeholders:
  Workstations:
    - PC*
    - LAP*
  Servers: SRV*
[...]
```
Would replace:

* `ComputerName: %Workstations%` with `ComputerName:("PC*" "LAP*")`
* `ComputerName: %Servers%` with `ComputerName:SRV*`

**Comment by thomaspatzke** [comment]
Dropped this requirement after several discussions. This is something that should be present in lists inside of the SIEM instead of generated queries.

**Comment by christophetd** [comment]
I think this would still be a great enhancement to have when you have multiple SIEM instances deployed (e.g. if you're a MSSP) and want to be able to do some whitelisting in a centralized manner.

Sample use:

```yaml
# new-service.yml

title: Service Installation
description: Detects new Windows services
logsource:
    product: windows
    service: system
detection:
    selection:
        EventID: 4697
    
    known_services: 
        ServiceFileName: '%known_services%'

    condition: selection and not known_services
falsepositives: []
level: low
```

```yaml
# customer1.yml
logsources:
  windows:
    product: windows
    index: windows_*
    
placeholders:
  known_services:
    - 'C:\Windows\System32\xxx.sys'
```

```yaml
# customer2.yml
logsources:
  windows:
    product: windows
    index: windows-basic-*
    
placeholders:
  known_services:
    - 'C:\Windows\System32\yyy.sys'
```

I'm open to implementing support for this and propose a PR, please let me know your thoughts!
