### ISSUE TITLE
Qradar Custom Field Mappings

### ISSUE THREAD

**Issue by m0jtaba** [Neo23x0/sigma#222]
I am looking for a way to change the current field mappings to a qradar field mappings an example of this would be: 
**EventID: EventIDCode**
or
**EventID: Event ID Code**

I looked at the wiki where it mentions the custom field mappings so I assumed I could do the following by appending a custom field for EventID in this file: **Neo23x0_Sigma/sigma/tools/config/qradar.yml**
with this key mappings:
```
fieldmappings:
    EventID:
        - EventIDCode
    dst:
        - destinationIP
    dst_ip:
        - destinationIP
    src:
        - sourceIP
    src_ip:
        - sourceIP 
```
Command:
```
python3.7 ../../../tools/sigmac -t qradar win_rare_service_installs.yml
```
Output:
```
SELECT count(ServiceName) as agg_val from events where EventID='7045' group by ServiceName having agg_val < 5
```
Expected outcome:
```
SELECT count(ServiceName) as agg_val from events where EventIDCode='7045' group by ServiceName having agg_val < 5
```
Where am I going wrong with this?
