### ISSUE TITLE
Checking for incorrect usage of 'selection' keyword in condition field

### ISSUE THREAD

**Issue by keepwatch** [Neo23x0/sigma#251]
While testing `sigmac` output to Splunk for [win_spn_enum.yml](https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_spn_enum.yml), I noticed some unexpected output.

For simplicity, I'll include the relevant rule text here:
```
detection:
    selection:
         Image: '*\setspn.exe'
    selection1:
        Description: '*Query or reset the computer* SPN attribute*'
    cmd:
        CommandLine: '*-q*'
    condition: (selection or selection1) and cmd 
---
logsource:
    product: windows
    service: sysmon
detection:
    selection:
        EventID: 1
```

For this condition, `sigmac` outputs: `(index="sysmon" ((EventID="1" TargetImage="*\\setspn.exe") OR Description="*Query or reset the computer* SPN attribute*") CommandLine="*-q*")`. However, `((EventID="1" TargetImage="*\\setspn.exe")` is incorrect, the EventID should be ANDed with all the other conditions. I'll submit a PR to fix the rule.

I checked the repo for other rules that might have the same issue (`grep -r "condition:" sigma/rules/* | grep selection | grep "("`), and couldn't find anything, although this seems like an easy mistake for people who don't know YARA well (like me 😄 ). 

Perhaps there should be a build test in the future for this? Something like "where multiple log sources exist, selection must be at the root level of the condition".
