### ISSUE TITLE
ConditionalFieldMapping for Null values.

### ISSUE THREAD

**Issue by duzvik** [Neo23x0/sigma#326]
Hello, I'm trying to create sigma  rule:
```
detection:
    selection:
      EventID: 13
      TargetObject: '*\SomeValue'
    filter:
      Details: null
condition: selection and not filter

```

With the following mapping:
```
EventID: event_id
TargetObject: registry_key_path
Details:
        EventID=13: registry_key_value
```

I'm expecting to get a query:
`
((event_id:"13" AND registry_key_path.keyword:*\\ SomeValue) AND NOT (NOT _exists_:registry_key_value))`

But **Details** fields don't  get mapped to **registry_key_value**

In SigmaParser: https://github.com/Neo23x0/sigma/blob/6918784e87e37c1bd827d74dbed284d80ed9483b/tools/sigma/parser/rule.py#L85

For null values SigmaParser use **mapping.resolve_fieldname**,  but **ConditionalFieldMapping::resolve_fieldname**  get mapped value only  from default config value: https://github.com/Neo23x0/sigma/blob/6918784e87e37c1bd827d74dbed284d80ed9483b/tools/sigma/config/mapping.py#L133

For workaround I can use following mapping:
```
    Details:
        default: "registry_key_value"

```

But I'm sure that  SigmaParser for  null values should use conditional mapping, not only default value
