### ISSUE TITLE
sigmac ElastAlert - Wrong field mapping on Conditional Field Mappings

### ISSUE THREAD

**Issue by architect00** [Neo23x0/sigma#332]
**Sigma Repo Version**: `commit 763939a8ca9f66e08035d68ad9ed76edad082e0d, Date:   Wed Apr 24 23:53:02 2019 +0200`

**Problem Description:**
We convert the rule `rules/windows/builtin/win_susp_failed_logons_single_source.yml` with the target **elastalert** with the following custom field mappings:

```yaml
fieldmappings:
    EventID: event.id
    LogonProcessName:
        EventID=4624: process.process_name
    LogonType: logon_type
    UserName:
        EventID=529: failed_account
        EventID=4625: failed_account
        EventID=4776: logon_account
    Workstation:
        EventID=4776: source_workstation
    WorkstationName:
        EventID=529: network.workstation_name
        EventID=4625: network.workstation_name
        EventID=4776: source_workstation
```

```bash
./sigmac -t elastalert -c config/custom_mappings.yml ../rules/windows/builtin/win_susp_failed_logons_single_source.yml
```

The field mappings are not translated correctly, if we implement conditionals like UserName, Workstation, WorkstationName.

**Actual result:**
```yaml
alert:
- debug
buffer_time:
  hours: 24
description: Detects suspicious failed logins with different user accounts from a
  single source system
doc_type: doc
filter:
- query:
    query_string:
      query: (event.id:("529" "4625") AND logon_account.keyword:* AND source_workstation.keyword:*)
index: tryout-*
max_threshold: 3
metric_agg_key: UserName.keyword
metric_agg_type: cardinality
name: Multiple-Failed-Logins-with-Different-Accounts-from-Single-Source-System_0
priority: 3
query_key: WorkstationName.keyword
realert:
  minutes: 0
type: metric_aggregation

alert:
- debug
buffer_time:
  hours: 24
description: Detects suspicious failed logins with different user accounts from a
  single source system
doc_type: doc
filter:
- query:
    query_string:
      query: (event.id:"4776" AND logon_account.keyword:* AND source_workstation.keyword:*)
index: tryout-*
max_threshold: 3
metric_agg_key: UserName.keyword
metric_agg_type: cardinality
name: Multiple-Failed-Logins-with-Different-Accounts-from-Single-Source-System_1
priority: 3
query_key: Workstation.keyword
realert:
  minutes: 0
type: metric_aggregation
```

**Expected results:**
```yaml
alert:
- debug
buffer_time:
  hours: 24
description: Detects suspicious failed logins with different user accounts from a
  single source system
doc_type: doc
filter:
- query:
    query_string:
      query: (event.id:("529" "4625") AND failed_account.keyword:* AND network.workstation_name.keyword:*)
index: tryout-*
max_threshold: 3
metric_agg_key: failed_account.keyword
metric_agg_type: cardinality
name: Multiple-Failed-Logins-with-Different-Accounts-from-Single-Source-System_0
priority: 3
query_key: network.workstation_name.keyword
realert:
  minutes: 0
type: metric_aggregation

alert:
- debug
buffer_time:
  hours: 24
description: Detects suspicious failed logins with different user accounts from a
  single source system
doc_type: doc
filter:
- query:
    query_string:
      query: (event.id:"4776" AND logon_account.keyword:* AND source_workstation.keyword:*)
index: tryout-*
max_threshold: 3
metric_agg_key: logon_account.keyword
metric_agg_type: cardinality
name: Multiple-Failed-Logins-with-Different-Accounts-from-Single-Source-System_1
priority: 3
query_key: source_workstation.keyword
realert:
  minutes: 0
type: metric_aggregation
```

**Additional Information:**
Looking into the code, we suspect the root cause might be in the file `tools/sigma/backends/elasticsearch.py` on line [635](https://github.com/Neo23x0/sigma/blob/763939a8ca9f66e08035d68ad9ed76edad082e0d/tools/sigma/backends/elasticsearch.py#L635) and [646](https://github.com/Neo23x0/sigma/blob/763939a8ca9f66e08035d68ad9ed76edad082e0d/tools/sigma/backends/elasticsearch.py#L646), because no field translations seem to be used on those `parsed.parsedAgg.*` properties.

**Comment by strassi** [comment]
I researched the code and probably found the issue:

in `tools/sigma/parser/rule.py` on [line 84](https://github.com/Neo23x0/sigma/blob/5dfe39c05b2a8555b2856cc10b206482b407530a/tools/sigma/parser/rule.py#L84) `resolve` is called on [class FieldMappingChain](https://github.com/Neo23x0/sigma/blob/5dfe39c05b2a8555b2856cc10b206482b407530a/tools/sigma/config/mapping.py#L151) which calls `resolve` on [class ConditionalFieldMapping](https://github.com/Neo23x0/sigma/blob/5dfe39c05b2a8555b2856cc10b206482b407530a/tools/sigma/config/mapping.py#L67).

In [class ConditionalFieldMapping](https://github.com/Neo23x0/sigma/blob/5dfe39c05b2a8555b2856cc10b206482b407530a/tools/sigma/config/mapping.py#L67) in the function `resolve`:

```python
def resolve(self, key, value, sigmaparser):
        # build list of matching target mappings
        targets = set()
        for condfield in self.conditions:
            if condfield in sigmaparser.values:
                rulefieldvalues = sigmaparser.values[condfield] # contains values of both selections
                for condvalue in self.conditions[condfield]:
                    if condvalue in rulefieldvalues:
                        targets.update(self.conditions[condfield][condvalue]) # this overrides prior targets
```

The function above is not aware of the current **selection**, which it is working on. In our case
it executes `targets.update` even though, the EventID is not used in the current **selection**.

My temporary tested fix (at least for the `query_string` not the aggregations) uses a set property on `sigmaparser`  and conditionals before `targets.update`:

`tools/sigma/parser/rule.py` [Starting Line 83](https://github.com/Neo23x0/sigma/blob/5dfe39c05b2a8555b2856cc10b206482b407530a/tools/sigma/parser/rule.py#L83)
```python
                mapping = self.config.get_fieldmapping(key)
                self.current_definition = definition # set current definition / selection
                cond.add(mapping.resolve(key, value, self)) # start resolving
```

`tools/sigma/config/mapping.py` [Starting Line 115](https://github.com/Neo23x0/sigma/blob/5dfe39c05b2a8555b2856cc10b206482b407530a/tools/sigma/config/mapping.py#L115)
```python
                for condvalue in self.conditions[condfield]:
                    if self.find(condvalue, rulefieldvalues):
                        # Checking if condvalue is actually used in the current selection
                        if type(sigmaparser.current_definition[condfield]) == list:     # if multiple items
                            if int(condvalue) not in sigmaparser.current_definition[condfield]:
                                continue
                        else:
                            if int(condvalue) != sigmaparser.current_definition[condfield]: # if single value
                                continue
                        targets.update(self.conditions[condfield][condvalue])     # update the targets
```

Now this fix looks pretty messed up, because I'm not a professional software engineer and it does not fix the problem on the aggregations.

Does anyone of you guys have any suggestions how to solve that?

**Comment by architect00** [comment]
I found a partial workaround for the issue to fix the query field mappings. The aggregation key mappings still do not work correctly. Using a [collection file](https://github.com/Neo23x0/sigma/wiki/Specification#rule-collections) causes the sigma converter to produce the desired output.

My collection file looks like this one:
```yaml
# win-susp-failed-logons.yml
---
action: global
title: Multiple Failed Logins for one Account
description: Detects suspicious failed logins for one user accounts in a given timeframe 
status: experimental
falsepositives:
    - Terminal servers
    - Jump servers
    - Other multiuser systems like Citrix server farms
    - Workstations with frequently changing users 
level: medium
---
logsource:
    product: windows
    service: security
detection:
    selection:
        EventID: 4625
        UserName: '*'
    condition:
            - selection | count(UserName) > 9
---
action: repeat
detection:
    selection:
        EventID: 4776
---
action: repeat
detection:
    selection:
        EventID: 529
---
action: reset
```

Using `sigmac -t elastalert -c your_fieldmappings.yml win-susp-failed-logons.yml` produces the following _elastalert_ rules:

```yaml
alert:
- debug
buffer_time:
  minutes: 30
description: Detects suspicious failed logins for one user accounts in a given timeframe
doc_type: doc
filter:
- query:
    query_string:
      query: (event.id:"4625" AND (failed_account.account_name_pseudonym.keyword:*
        OR failed_account.account_name.keyword:*))
index: adlog-*
max_threshold: 9
metric_agg_key: UserName.keyword
metric_agg_type: cardinality
name: Multiple-Failed-Logins-for-one-Account_0
priority: 3
realert:
  minutes: 0
type: metric_aggregation

alert:
- debug
buffer_time:
  minutes: 30
description: Detects suspicious failed logins for one user accounts in a given timeframe
doc_type: doc
filter:
- query:
    query_string:
      query: (event.id:"4776" AND (logon_account_pseudonym.keyword:* OR logon_account.keyword:*))
index: adlog-*
max_threshold: 9
metric_agg_key: UserName.keyword
metric_agg_type: cardinality
name: Multiple-Failed-Logins-for-one-Account-2_0
priority: 3
realert:
  minutes: 0
type: metric_aggregation

alert:
- debug
buffer_time:
  minutes: 30
description: Detects suspicious failed logins for one user accounts in a given timeframe
doc_type: doc
filter:
- query:
    query_string:
      query: (event.id:"529" AND failed_account.keyword:*)
index: adlog-*
max_threshold: 9
metric_agg_key: UserName.keyword
metric_agg_type: cardinality
name: Multiple-Failed-Logins-for-one-Account-3_0
priority: 3
realert:
  minutes: 0
type: metric_aggregation
```
