### ISSUE TITLE
Elastalert Backend - Query Syntax

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Neo23x0/sigma#343]
Good afternoon Sigma Team,

I have been testing a few rules created by Sigmac, and I am getting hits on strings that do not match 100% what is provided via the SIGMA rule. For example:
Rule: https://github.com/Neo23x0/sigma/blob/81515b530cc8e359d5fa3df541145c2670ba9229/rules/windows/builtin/win_alert_mimikatz_keywords.yml
```
title: Mimikatz Use
description: This method detects mimikatz keywords in different Eventlogs (some of them only appear in older Mimikatz version that are however still used by different threat groups)
author: Florian Roth
tags:
    - attack.s0002
    - attack.t1003
    - attack.lateral_movement
    - attack.credential_access
logsource:
    product: windows
detection:
    keywords:
        - mimikatz
        - mimilib
        - <3 eo.oe
        - eo.oe.kiwi
        - privilege::debug
        - sekurlsa::logonpasswords
        - lsadump::sam
        - mimidrv.sys
    condition: keywords
falsepositives:
    - Naughty administrators
    - Penetration test
level: critical
```

Translated by Sigmac (Elastalert Backed) to:
```
alert:
- debug
description: This method detects mimikatz keywords in different Eventlogs (some of
  them only appear in older Mimikatz version that are however still used by different
  threat groups)
filter:
- query:
    query_string:
      query: (mimikatz OR mimilib OR 3\ eo.oe OR eo.oe.kiwi OR privilege\:\:debug
        OR sekurlsa\:\:logonpasswords OR lsadump\:\:sam OR mimidrv.sys)
index: logs-*
name: Mimikatz-Use_0
priority: 1
realert:
  minutes: 0
type: any
```

I was getting a few hits:
![image](https://user-images.githubusercontent.com/9653181/57972898-65099100-796e-11e9-9af1-5ca44390e592.png)

I ran the query from the elastalert rule in the Kibana search bar
```
mimikatz OR mimilib OR 3\ eo.oe OR eo.oe.kiwi OR privilege\:\:debug         OR sekurlsa\:\:logonpasswords OR lsadump\:\:sam OR mimidrv.sys
``` 
and got the following:

![image](https://user-images.githubusercontent.com/9653181/57972922-bb76cf80-796e-11e9-9403-1c740505dac4.png)

![image](https://user-images.githubusercontent.com/9653181/57972924-c893be80-796e-11e9-8312-7e8d0ebe8c1e.png)

![image](https://user-images.githubusercontent.com/9653181/57972926-d5181700-796e-11e9-8af1-3ddb8c74cdad.png)

I believe (not 100% sure), rules translated to Elastalert like that are taking a little longer than expected and are causing other issues with Elasticsearch such as:

https://github.com/Yelp/elastalert/issues/2249
