### ISSUE TITLE
Es-dsl wildcards: Backslash and Asterisk

### ISSUE THREAD

**Issue by qux-bbb** [Neo23x0/sigma#387]
My raw sigma rule(test.yml) is:  
```yml
title: Test
status: experimental
description: Test Backslash and Asterisk
author: Test
logsource:
    product: windows
    service: sysmon
detection:
    selection:
        EventID: 13
        TargetObject: 
            - '*\Desktop\hello\*word'
    condition: selection
level: high
```
Use this to convert it to dsl file(test.json):
```sh
py -3 sigmac --target es-dsl -c elk-winlogbeat test.yml -o test.json
```
The result is:
```json
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must": [
            {
              "match_phrase": {
                "log_name": "Microsoft-Windows-Sysmon/Operational"
              }
            },
            {
              "match_phrase": {
                "event_id": "13"
              }
            },
            {
              "bool": {
                "should": [
                  {
                    "wildcard": {
                      "event_data.TargetObject.keyword": "*\\Desktop\\hello\\*word"
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    }
  }
}
```
When I search by this json, it's not working.

**Comment by qux-bbb** [comment]
If I change yml to this:  
```yml
title: Test
status: experimental
description: Test Backslash and Asterisk
author: Test
logsource:
    product: windows
    service: sysmon
detection:
    selection:
        EventID: 13
        TargetObject: 
            - '*\\Desktop\\hello\\\*word'
    condition: selection
level: high
```
It will turn to:  
```json
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must": [
            {
              "match_phrase": {
                "log_name": "Microsoft-Windows-Sysmon/Operational"
              }
            },
            {
              "match_phrase": {
                "event_id": "13"
              }
            },
            {
              "bool": {
                "should": [
                  {
                    "wildcard": {
                      "event_data.TargetObject.keyword": "*\\\\Desktop\\\\hello\\\\\\*word"
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    }
  }
}
```
And it works.
