### ISSUE TITLE
Timeframe cannot be included in condition list

### ISSUE THREAD

**Issue by zouzias** [Neo23x0/sigma#395]
***Sigma Repo Version***: commit 2b062a0de72d11259416bcd01c7f7b4dc06fb7d8, Date: Thu Jul 11 14:42:45 CEST 2019
***sigmatools*** version: 0.11

### Problem Description:
Cannot add a `timeframe` in list of conditions.

Adding a `timeframe: 15s` condition on rule `rules/windows/builtin/win_alert_active_directory_user_control.yml`, i.e., 

```
diff --git a/rules/windows/builtin/win_alert_active_directory_user_control.yml b/rules/windows/builtin/win_alert_active_directory_user_control.yml
index cb39ccf..e31ce87 100644
--- a/rules/windows/builtin/win_alert_active_directory_user_control.yml
+++ b/rules/windows/builtin/win_alert_active_directory_user_control.yml
@@ -11,6 +11,7 @@ logsource:
     service: security
     definition: 'Requirements: Audit Policy : Policy Change > Audit Authorization Policy Change, Group Policy : Computer Configuration\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Policy Change\Audit Authorization Policy Change'
 detection:
+    timeframe: 15s
     selection:
         EventID: 4704
     keywords:
```

Actual rule is:

```
title: Enabled User Right in AD to Control User Objects
description: Detects scenario where if a user is assigned the SeEnableDelegationPrivilege right in Active Directory it would allow control of other AD user objects.
tags:
    - attack.privilege_escalation
    - attack.t1078
references:
    - https://www.harmj0y.net/blog/activedirectory/the-most-dangerous-user-right-you-probably-have-never-heard-of/
author: '@neu5ron'
logsource:
    product: windows
    service: security
    definition: 'Requirements: Audit Policy : Policy Change > Audit Authorization Policy Change, Group Policy : Computer Configuration\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Policy Change\Audit Authorization Policy Change'
detection:
    timeframe: 15s
    selection:
        EventID: 4704
    keywords:
        - 'SeEnableDelegationPrivilege'
    condition: all of them
falsepositives: 
    - Unknown
level: high
```
Run `sigmac -t es-dsl -c tools/config/elk-linux.yml  rules/windows/builtin/win_alert_active_directory_user_control.yml`.

### Actual result:
```
Sigma parse error in rules/windows/builtin/win_alert_active_directory_user_control.yml: Expected map or list, got type <class 'str'>: '15s'`
```
### Expected results:

```
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must": [
            {
              "multi_match": {
                "query": "SeEnableDelegationPrivilege",
                "fields": [],
                "type": "phrase"
              }
            },
            {
              "match_phrase": {
                "EventID": "4704"
              }
            },
            {
              "range": {
                "date": {
                  "gte": "now-15s"
                }
              }
            }
          ]
        }
      }
    }
  }
}

```

Additional Information:
Workaround is to not include the timeframe in the conditions, i.e.,

```
title: Enabled User Right in AD to Control User Objects
description: Detects scenario where if a user is assigned the SeEnableDelegationPrivilege right in Active Directory it would allow control of other AD user objects.
tags:
    - attack.privilege_escalation
    - attack.t1078
references:
    - https://www.harmj0y.net/blog/activedirectory/the-most-dangerous-user-right-you-probably-have-never-heard-of/
author: '@neu5ron'
logsource:
    product: windows
    service: security
    definition: 'Requirements: Audit Policy : Policy Change > Audit Authorization Policy Change, Group Policy : Computer Configuration\Windows Settings\Security Settings\Advanced Audit Policy Configuration\Audit Policies\Policy Change\Audit Authorization Policy Change'
detection:
    timeframe: 15s
    selection:
        EventID: 4704
    keywords:
        - 'SeEnableDelegationPrivilege'
    condition: (selection and keywords)
falsepositives: 
    - Unknown
level: high
```
