### ISSUE TITLE
Invalid syntax for rules "APT29 Google Update Service Install" and "Chafer Activity"

### ISSUE THREAD

**Issue by joesecurity** [Neo23x0/sigma#465]
```
logsource:
    category: process_creation
    product: windows
detection:
    process:
        Image: 
            - 'C:\Program Files(x86)\Google\GoogleService.exe'
            - 'C:\Program Files(x86)\Google\GoogleUpdate.exe'

```

Is missing the condition directive. Likely there are more rules which do not comply with the specification. Another example is the rule "apt_chafer_mar18.yml", it contains kind of a top condition element:

```
detection:
    condition: 1 of them
```

The detection elements below again are missing the condition directive:

```
detection:
    selection_service:
        EventID: 7045
        ServiceName:
            - 'SC Scheduled Scan'
            - 'UpdatMachine'
```
It looks like the top detection element is a logic for the several "sub detections". Again this structure is not defined in the specification.
