### ISSUE TITLE
Wrong wild card escaping in rule win_malware_formbook.yml

### ISSUE THREAD

**Issue by joesecurity** [Neo23x0/sigma#466]
```
detection:
    selection:
        # Parent command line should not contain a space value
        # This avoids false positives not caused by process injection
        # e.g. wscript.exe /B sysmon-install.vbs
        ParentCommandLine: 'C:\Windows\System32\*.exe'
        CommandLine: 
            - '*\cmd.exe /c del "C:\Users\*\AppData\Local\Temp\*.exe'
            - '*\cmd.exe /c del "C:\Users\*\Desktop\*.exe'
``` 

According to specification \* is an escape * char. If some wildcard after a backspace should be searched, the backslash has to be escaped: \\*. So the correct would be:

```
detection:
    selection:
        # Parent command line should not contain a space value
        # This avoids false positives not caused by process injection
        # e.g. wscript.exe /B sysmon-install.vbs
        ParentCommandLine: 'C:\Windows\System32\\*.exe'
        CommandLine: 
            - '*\cmd.exe /c del "C:\Users\\*\AppData\Local\Temp\\*.exe'
            - '*\cmd.exe /c del "C:\Users\\*\Desktop\\*.exe'
```
