### ISSUE TITLE
Linux auditd rules

### ISSUE THREAD

**Issue by j91321** [Neo23x0/sigma#539]
Hi,
My original intention was to write auditbeat config for sigmac to use with auditd rules. What a rabbit hole. 

The problem I have encountered is that making any reasonable mapping between the current fields (which are for auditd) and auditbeat is not ideal because auditbeat is not a parser for the auditd logs, but registers itself as consumer with Linux Auditing System.

I ended up rewriting most of the rules with more generic field names such as process name, executable and args. 

The rules now look like this:

```
title: Masquerading as Linux crond process
id: 9d4548fa-bba0-4e88-bd66-5d5bf516cda0
status: experimental
description: Masquerading occurs when the name or location of an executable, legitimate or malicious, is manipulated or abused for the sake of evading defenses and
    observation. Several different variations of this technique have been observed.
author: Timur Zinniatullin, oscd.community
date: 2019/10/21
references:
    - https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1036/T1036.yaml
logsource:
    product: linux
    service: auditd
detection:
    selection:
        syscall: 'execve'
        name: 'cp'
        args: 
          - '-i'
          - '/bin/sh'
          - '*/crond'
    condition: selection
level: medium
tags:
    - attack.defense_evasion
    - attack.t1036
```
Rules can be found [here](https://github.com/j91321/sigma/tree/auditbeat-config/rules/linux/auditd) and the auditbeat config [here](https://github.com/j91321/sigma/blob/auditbeat-config/tools/config/auditbeat.yml)
They work quite nicely when provided .keyword blacklist. (can provide results if necessary)

With the right rules for the Linux Auditing System most of the other linux rules which are now just keyword searches could be rewritten. Which I believe would solve part of [Rework rules which aren't bound to a field](https://github.com/Neo23x0/sigma/issues/501)

Other solution can be to create these rules as generic linux rules with logsource linux-auditing-system and leave the current auditd rules as they are.

I would like a feedback on this before making PR on what is the right direction to take to make sure the rules stay generic enough for sigma and can be used with other backends not just Elasticsearch. Also I would like to know if anybody uses the auditd rules in the current state and how.
