### ISSUE TITLE
Regular expression support

### ISSUE THREAD

**Issue by 59e5aaf4** [Neo23x0/sigma#540]
We need regular expressions to avoid the vendor lock-in in FireEye's HX (Close to OpenIOC) XML IOCs. I believe the regular expression version we're using is PCRE, but nothing is sure about this. There are a lot of meanings for "regular expression", https://www.regular-expressions.info/posix.html has a good list of the existing implementations. (And even PCRE isn't exactly Perl compatible, see https://www.regular-expressions.info/pcre.html 🙃  )

As per https://github.com/Neo23x0/sigma/issues/401#issuecomment-512282986 :

> * we are working on the extensions.
> * REs cannot be used yet.

So the question still remains:
* What is to be done to gain regex support in Sigma ?

YAML doesn't seem to have a specific type for regexes, and string could be fine to store regexes. But then, how could we differentiate regexes from the rest of the patterns ?

Proposal (not great but does the job?): using them as standalone verbs with prefixes, whatever detection rule starts with `regex_` is a regex.

```yaml
detection: all of selection0* and regex_1
selection0_0:
  someField: process.exe
selection0_1:
  otherField: specificValue
regex_1:
  thirdField: /MyReg(ex*)/
```

Comments ? Ideas ? Thanks !
