### ISSUE TITLE
[Rules Development Backlog] Develop Sigma rules for Invoke-DOSfuscation

### ISSUE THREAD

**Issue by yugoslavskiy** [Neo23x0/sigma#577]
- Tool: [Invoke-DOSfuscation](https://github.com/danielbohannon/Invoke-DOSfuscation) — cmd.exe command obfuscation framework
- Author: Daniel Bohannon, [@danielhbohannon](https://twitter.com/danielhbohannon)
- Type: Offensive tool, threat simulation

The majority (>50%) of Sigma rules are based on command-line events (WEL Security Event ID 4688 and Sysmon Event ID 1), but the presence of Sigma rules for cmd.exe command Obfuscation Indicators detection is quite limited.

There is only one Sigma rule that is focusing on cmd.exe commandline obfuscation detection — [rules/windows/process_creation/win_susp_cli_escape.yml](https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_susp_cli_escape.yml). The most of the methods, supported by [Invoke-DOSfuscation](https://github.com/danielbohannon/Invoke-DOSfuscation) are not covered at all.

You can pick up some of the methods of cmd.exe commandline obfuscation, provided by the [Invoke-DOSfuscation](https://github.com/danielbohannon/Invoke-DOSfuscation) framework and develop Sigma rules for them. You will need to use [regular expressions](https://github.com/Neo23x0/sigma/wiki/Specification#types) in Sigma rules. 
Here is a [Sigma rule](https://github.com/Neo23x0/sigma/blob/oscd/rules/windows/process_creation/win_invoke_obfuscation_obfuscated_iex_commandline.yml) developed by Daniel Bohannon that utilize regular expressions in Sigma rule:

```
title: Invoke-Obfuscation obfuscated IEX invocation
id: 4bf943c6-5146-4273-98dd-e958fd1e3abf
description: "Detects all variations of obfuscated powershell IEX invocation code generated by Invoke-Obfuscation framework from the following code block \u2014 https://github.com/danielbohannon/Invoke-Obfuscation/blob/master/Out-ObfuscatedStringCommand.ps1#L873-L888"
status: experimental
author: Daniel Bohannon (@Mandiant/@FireEye), oscd.community
date: 2019/11/08
tags:
    - attack.defense_evasion
    - attack.t1027
logsource:
    product: windows
    service: process_creation
detection:
    selection:
        - CommandLine|re: '\$PSHome\[\s*\d{1,3}\s*\]\s*\+\s*\$PSHome\['
        - CommandLine|re: '\$ShellId\[\s*\d{1,3}\s*\]\s*\+\s*\$ShellId\['
        - CommandLine|re: '\$env:Public\[\s*\d{1,3}\s*\]\s*\+\s*\$env:Public\['
        - CommandLine|re: '\$env:ComSpec\[(\s*\d{1,3}\s*,){2}'
        - CommandLine|re: '\*mdr\*\W\s*\)\.Name'
        - CommandLine|re: '\$VerbosePreference\.ToString\('
        - CommandLine|re: '\String\]\s*\$VerbosePreference'
    condition: selection
falsepositives:
    - Unknown
level: high
```
