### ISSUE TITLE
conversion type for RSA not works properly

### ISSUE THREAD

**Issue by RazviAlex** [Neo23x0/sigma#712]
Hi everyone,

I'm new in this world and I'm trying to convert a simple rule in netwitness SIEM. The rule is:

```
title: Port Scan
status: experimental
logsource:
  product: firewall
detection:
  condition: selection | count(dest_ip) > 10
  timeframe: 2m
  selection:
    dest_port:
    - 80
    - 443
fields:
- dest_ip
- dest_port
level: high
```
1º example, convert with:
`/sigmac -v -t netwitness ../rules/portScan.yml `
Result:
`(dest_port = '80', '443')`

So the 'dest_port' it's wrong in netwitness the good one is '**ip.dstport**'. I try then using the '-c' config and select netwiness.yml.
2º example:
`/sigmac -v -t netwitness -c ../tools/config/netwitness.yml ../rules/portScan.yml `
But same result:
`(dest_port = '80', '443')`

Don't understand why it gives me 'dest_port' instead of 'ip.dstport' in the 2 example.

Thank you for any help!
