### ISSUE TITLE
sigmac throw  Unexpected token [ Token: ID: 'dllload1' ] for rules/windows/sysmon/sysmon_mimikatz_inmemory_detection.yml

### ISSUE THREAD

**Issue by tagashy** [Neo23x0/sigma#82]
sigmac give the following error when using it to parse the rule mimikatz_inmemory_detection.yml.
```
[tagashy@manjaro シグマ]$ sigmac -t es-qs sigma_rule.yml 
Sigma parse error in sigma_rule.yml: Unexpected token [ Token: ID: 'dllload1' ] at 12 in aggregation expression
```
sigma_rule .yml is mimikatz_inmemory_detection.yml but if the content is needed it's the following :
```yaml
title: Mimikatz In-Memory Detection
status: experimental
description: Detects certain DLL loads when Mimikatz gets executed
reference: https://securityriskadvisors.com/blog/post/detecting-in-memory-mimikatz/
logsource:
    product: sysmon
detection:
    selector:
        EventID: 7
        Image: 'C:\Windows\System32\rundll32.exe'
    dllload1:
        ImageLoaded: '*\vaultcli.dll'
    dllload2:
        ImageLoaded: '*\wlanapi.dll'
    exclusion:
        ImageLoaded:
            - 'ntdsapi.dll'
            - 'netapi32.dll'
            - 'imm32.dll'
            - 'samlib.dll'
            - 'combase.dll'
            - 'srvcli.dll'
            - 'shcore.dll'
            - 'ntasn1.dll'
            - 'cryptdll.dll'
            - 'logoncli.dll'
    timeframe: last 30s
    condition: selector | dllload1 and dllload2 and not exclusion
falsepositives:
    - unknown
level: medium
```

for my instalation i've installed it through :
`pip install sigma && pip install sigmatools`
